---
# ~/.knownhostsinator/ansible-role-knownhosts.yml

# source: https://github.com/knownhostsinator/knownhostsinator/blob/master/spec/fixtures/sample.yml
# source: https://github.com/luismayta/dotfiles/blob/develop/.knownhostsinator.yml

name: ansible-role-knownhosts
root: ~/dev/bossjones/ansible-role-knownhosts
knownhosts_options: -2
# set-option -g default-shell /usr/local/bin/zsh

# Runs on project start, always
# on_project_start: make environment

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window:
  - exec zsh

# Optional knownhosts socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
# on_project_start: make environment

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from knownhosts session )
# on_project_exit: make docker.down

# Run on project stop
# on_project_stop: make docker.down

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: pipenv shell --fancy

# Pass command line options to knownhosts. Useful for specifying a different knownhosts.conf.
# knownhosts_options: -f ~/.knownhosts.mac.conf

# Change the command to call knownhosts.  This can be used by derivatives/wrappers like byobu.
# knownhosts_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.


windows:
  - neofetch:
      layout: 9fa4,223x75,0,0{118x75,0,0[118x52,0,0{59x52,0,0,8,58x52,60,0,13},118x22,0,53,12],104x75,119,0[104x16,119,0,1,104x15,119,17,9,104x22,119,33,2,104x19,119,56,3]}
      panes:
        - neofetch:
            - pwd
        - pwd:
            - pwd
        - pwd:
            - pwd
            - pwd
